### PR TITLE
New API for locale-invariant floating point variables

### PR DESCRIPTION
**Pull request by herrfrei**
I'd like to import data from Teslamate (for Tesla electric vehicle) via API calls and got problems with the floating point variable representation on Windows 10 with German locale. These are sent and expected as `10,7` (with comma) what is useful for API usage. 

As consequence, I added a new API controller under `/api/v2/` path that sends and receives numeric and boolean values directly as JSON (not stringified). DateTime values are currently formatted as "yyyy-MM-dd" strings (time is removed since GUI also does not support setting the time value).

### CODE REVIEW

**Comment by hargata** [comment]
"+928" yeah we're not reviewing/merging this.

Very confused as to what this actually accomplishes.

**Comment by herrfrei** [comment]
No, it's for sending/receiving decimals directly in JSON in a culture-invariant manner. Without this, the content, for instance the gas records, must be formatted according to the locale of the server. Means costs as '12,5' with de_DE and as '12.5' with en_EN. But the API should be invariant, hence this PR.

The datetime format was also added to have a locale-invariant string on all systems.

**Comment by hargata** [comment]
@herrfrei kk, I get what you mean, there is a far more elegant method of implementing this without needing to create brand new 
objects and a new API version. See PR #753 

That PR will allow for POST and PUT methods to take in a JSON body with datatypes, accomplished via JsonConverters, without breaking any existing implementations.

The GET methods; however, that will require further thinking/research.

**Comment by hargata** [comment]
Follow up on this:

On the next release, you will have the option of either setting an environment variable or passing in a `culture-invariant` key in your headers that will determine if the body that returns is invariant or culturally sensitive:

culturally invariant

Which means the entire scope of this PR is now covered by #753

**Comment by herrfrei** [comment]
@hargata Thank you for your PR. It's a different approach, I didn't want to change the original API. 
I tried the new branch and have two comments:

- (at least) in the gas records the case of the key's first letter has changed (upper case vs. lower before)
- `FuelEconomy` in gas records is still a string

```json
{
  "Id": 1,
  "Date": "2024-12-03",
  "Odometer": 1234,
  "FuelConsumed": 32.3,
  "Cost": 8.14,
  "FuelEconomy": "0",
  "IsFillToFull": false,
  "MissedFuelUp": false,
  "Notes": null,
  "Tags": null,
  "ExtraFields": [
  ]
}
```

**Comment by hargata** [comment]
@herrfrei fixed in #754

**Pull request closed without merging**
