### PR TITLE
Added translation logic for "Upload documents(optional)" in _UpgradeRecordModal.cshtml

### PR DESCRIPTION
**Pull request by Scorpoon**
In _UpgradeRecordModal.cshtml the translation logic was missing for "Upload documents(optional)"

### CODE REVIEW

**Comment by Scorpoon** [comment]
Added a bunch of code cleanup, see the 2nd commit.
Most of it is only fixing code warnings, introducing const strings for often used strings, introducing a function for the often used "OperationResponse"-Type. So there shouldn't be any breaking changes.

**Comment by hargata** [comment]
Thanks for the PR, but we can't merge this. Your first commit was fine, but your second commit has scope issues. You cannot submit a PR with 500+ line changes and describe it as 'a bunch of code cleanup', because 

1. We're not going to review a PR that large masquerading as a small fix.
2. We don't fully understand the reasoning behind some of the changes.

**Comment by Scorpoon** [comment]
Would it be okay to split the changes up? So a PR for the first commit and additionally split up my 2nd commit into a few PR. Then it's maybe easier to review and I also can give you better reasoning for the change?

**Comment by hargata** [comment]
Yes please split up the commits into incremental changes that are easier to review.

**Pull request closed without merging**
